### ISSUE TITLE
Question about @use

### ISSUE THREAD

**Issue by wcDogg** [mayank99/open-props-scss#12]
Hello - Thank you for this project :) 

I have `./src/scss/styles.scss/`  with `@use 'open-props-scss' as op;` as the first line. When I run Sass, I get `Error: Can't find stylesheet to import.`

Have I misunderstood something?

**Comment by mayank99** [comment]
`@use 'open-props-scss'` assumes that you are using one of these two options:
- a **bundler**, such as [vite](https://vitejs.dev/) or webpack
- [**import maps**](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script/type/importmap), for aliasing the bare module path to a real one

if you provide more information about your project, i may be able to help.

**Comment by wcDogg** [comment]
Hi @mayank99  - here is an example repo: https://github.com/wcDogg/eleventy-test.

It's an Eleventy project and I'm not using webpack or other bundler - just Sass.  So I need an import map? 

Reading the MDN article, it's not clear to me how I'd set that up. 

I sincerely appreciate your help :)

**Comment by wcDogg** [comment]
Closing this - went with the PostCSS JIT props implementation - but I will be keeping an eye on this project :)
