### ISSUE TITLE
sass warnings about `/`

### ISSUE THREAD

**Issue by mayank99** [mayank99/open-props-scss#4]
all the aspect ratio variables use `/`. example: `16/9`. sass does not like this, and i think the recommendation is to use `list.slash`

see https://sass-lang.com/documentation/breaking-changes/slash-div

**Comment by BenDMyers** [comment]
+1

**Comment by mayank99** [comment]
Fixed in [`0.4.1`](https://github.com/mayank99/open-props-scss/releases/tag/v0.4.1) through [`45f16e`](https://github.com/mayank99/open-props-scss/commit/45f16e01aa4cb72ca84470b2c51847cd2e219070) 🥳

**Comment by BenDMyers** [comment]
It works like a charm! Thank you, @mayank99!
